stages:
  - format
  - validate
  - plan
  - apply

terraform_fmt:
  stage: format
  image: hashicorp/terraform:1.6

  script:
    - cd terraform
    - terraform fmt -check -recursive

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

terraform_validate:
  stage: validate
  image: hashicorp/terraform:1.6

  script:
    - cd terraform
    - terraform init
    - terraform validate

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

terraform_plan:
  stage: plan
  image: hashicorp/terraform:1.6

  script:
    - cd terraform
    - terraform init
    - terraform plan -out=tfplan

  artifacts:
    paths:
      - terraform/tfplan

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

terraform_apply:
  stage: apply
  image: hashicorp/terraform:1.6

  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
      allow_failure: false
